### PR TITLE
Fix for #49 and some cosmetics

### PR DESCRIPTION
**Pull request by sebastianhaberey**
New pull request without the import changes.

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
Pardon my ignorance, I've been out of the go ecosystem for a while - it seems like moving away from checked-in dependencies means transitive dependencies can change arbitrarily. Does dep have any mechanism to prevent this?

**Comment by sebastianhaberey** [comment]
Hi Zach,

tbh I'm new to Go, so I can't say I've used dep extensively. But I saw that it has a package lock file ([Gopkg.lock](https://golang.github.io/dep/docs/Gopkg.lock.html)) similar to yarn.lock etc. where the revision numbers are frozen. The documentation says "the Gopkg.lock acts as a reproducible build list" - so it should prevent arbitrary changes.

**Comment by zach-klippenstein** [comment]
Ah missed that file because I was reading on my phone. It's not clear to me why changing the entire dependency management tool was required for this fix though, could you elaborate?

**Comment by zach-klippenstein** [comment]
Also, this PR would be easier to approve if it were split up into multiple PRs (eg one for go update, one for dep version updates, etc). I see you already have separate commits so if you can post those as separate PRs I can merge some of the more straightforward changes sooner.

**Comment by sebastianhaberey** [comment]
Sure, no problem! At least that is what I want to say... the reality is that I still haven't found a good way to fork a Go project, create a pull request and run the pull request on Travis.

The internal packages, referenced via the full repository path (as is standard in Go) are getting into the way. Other people seem to have [experienced the same problem](https://github.com/golang/go/issues/20883).

The only way I see to create a pull request that passes the CI is to create a dedicated pull request branch in my repository that won't build, then create the pull request from that branch and see if it builds. Not my favorite workflow, but I'll give it a try with the dep-related changes.

I'll close this PR in favor of smaller ones.

**Pull request closed without merging**
